# Generated by Django 2.2.1 on 2020-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200507_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(blank=True),
        ),
    ]
